print ('Welcome to the MadLib generator!')

adjective_1 = raw_input ('Type in an adjective: ')
adjective_2 = raw_input ('Another adjective: ')
adjective_3 = raw_input ('And another adjective: ')
adjective_4 = raw_input ('One more adjective: ')
plural_animal = raw_input ('Plural animal (e.g., puppies): ')
verb = raw_input ('Now a verb: ')
plural_noun = raw_input('Now a plural noun: ')
first_name = raw_input('The first name of a woman musictian: ')
beverage = raw_input('A beverage: ')
body_part = raw_input ('And, finally, a plural body part: ')

#how to start a new line:
print('\nExcellent choices! etc.')
print(' ')
print('Excellent choices! Here is your story...')
print('_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ')
print('There once was a ' + adjective_1 + ' programmer named ' + first_name)
print('who wanted to build a ' + adjective_2 + ' mobile app to')
print('help ' + adjective_3 + ' '+ plural_animal + ' find new homes')
print(' ')
print(first_name + ' stayed all night, drinking a lot of')
print('caffeinated ' + beverage + ' as she worked and worked')
print('trying to complete her ' + adjective_4 + ' program.' )
print(' ')
print('Whenever ' + first_name + ' hit a dead end, she would')
print('exclaim *' + plural_noun + '*!')
print(' ')
print('But she was not discouraged, and after a quick break')
print('to ' + verb + ' and clear her head, she got back to work.')
print(' ')
print('By morning, when the sun started to rise, she let out a')
print('big yawn, and stretched her ' + body_part+'.')
print('Finally, she was done.')
print('_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ')